# -*- coding: utf-8 -*-
"""voicefile_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMrMvtL2NO0kR6Nfq6WwqbMiTgFvk8pC

# **상용 서비스**

- ***Google Cloud Speech-to-Text***
  - 스피터 다이어라이제이션(speaker diarization)기능으로 발화자가 바뀔 때를 감지하고 개별 음성을 번호로 라벨링
  - 전사 결과에서 각 단어에 개별 발화자에게 할당된 번호를 태그로 표시

- ***Microsoft Azure Speaker Recognition***
  - 음성 생체인식을 통해 고유한 음성 특성으로 발화자를 확인하고 식별 (사용 불가능)
  - 단일 발화자의 오디오 훈련 데이터로 등록 프로필 생성

- ***Veritone AI***
  - 오디오에서 발화자가 언제 바뀌는지, 그 발화자가 누구인지 식별하는 스피터 인식 엔진

# **오픈소스 모델**

- ***Whisper(OpenAI)***
  - 인간 수준의 견고성과 정확도를 가진 신경망 모델, 108개 언어를 인식하고 전사할 수 있는 범용 모델

- ***SpeechBrain***
  - 음성 인식, 강화, 분리, 스피커 다이어라이제이션 지원하는 오픈소스 툴킷

- ***Wav2Vec 2.0***
  - 페이스북에서 개발한 자기지도학습 기반 모델

- ***DeepSpeech***
  - Mozilla의 오픈소스 음성 인식 엔진

- ***VOSK***
  - 안드로이드, iOS, 라즈베리파이 및 서버용 정확한 오프라인 음성 인식 API

# **ORA platform**

- ***KoSpeech***: 한국어 특화 모델
  - PyTorch 기발의 모듈화되고 확장 가능한 종단간 한국어 자동 음성 인식 툴킷
  - 한국어에 특화되어 있어 노인들의 한국어 발음 패턴을 더 잘 학습할 수 있음 <br>
  [KsponSpeech에 대한 전처리 코드](https://github.com/sooftware/ksponspeech)

- ***Whisper + KoSpeech***
"""